# Generated by Django 4.2.2 on 2023-06-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincom_app', '0005_alter_ward_ward_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='date_entered',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
