# Generated by Django 4.2.2 on 2023-06-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincom_app', '0012_alter_pollingunit_date_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='long',
            field=models.CharField(max_length=355, null=True),
        ),
    ]
