# Generated by Django 4.2.2 on 2023-06-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincom_app', '0013_alter_pollingunit_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
