# Generated by Django 4.2.2 on 2023-06-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincom_app', '0014_alter_pollingunit_polling_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='date_entered',
            field=models.DateTimeField(),
        ),
    ]
